### ISSUE TITLE
Panic-reset in series

### ISSUE THREAD

**Issue by sylafrs** [apacha/sensor-fusion-demo#2]
Once a panic happens, it always happen 4-5 times in a row, do you have an idea how to reset the sensors so it won't happen again?

I'm actually coding a game within Unity3D with GoogleVR plugin

I use your code to bypass GoogleVR orientation (that has drift). 
It works well, but this panic issue is a huge problem for me :p

**Comment by apacha** [comment]
Have you tried commenting out the whole "panic"-code? Maybe you don't need it after all. I had this issue on my mobile phone that it took a long time to correct if i shook it heavily, so I implemented this "panic"-mode. I guess for normal motion it isn't required after all.

**Comment by apacha** [comment]
And actually, please verify that the underlying sensors don't jump (extremely). Because in that case, the algorithm is quite powerless and has to react to sudden jumps.

**Comment by sylafrs** [comment]
I tried, but the orientation becomes invalid (the orientation becomes really weird); also tried to reset every single variable from the provider.
I think the algo is powerless, but I try to find out if there is an Android method somewhere that could reset sensor values (haven't found one :/ )

I'll continue to search, if I find anything, I'll tell you :)

___________________

If you're curious, that's how I used the code in Unity : http://pastebin.com/b37M4jr4

**Comment by apacha** [comment]
So what exactly happens if you use the RotationVectorProvider as OrientationProvider which is the standard Android Sensor Fusion? Does it only drift, or does it jump as well?

**Comment by wangjianpeng** [comment]
@sylafrs  I have a problem when use unity3d with android, the gyro a, accelerate and gravity always jitter event i place the mobile device on desktop.  could you solve this problem ?

**Comment by apacha** [comment]
@sylafrs: I am afraid, that I can not help with your issue, apart from suggesting to remove the panic-filter (which is a kind of ad-hoc solution anyway to a problem that I faced on my Samsung Galaxy S2 during development). 
@wangjianpeng please contact sylafrs directly.
