### ISSUE TITLE
Not an issue...

### ISSUE THREAD

**Issue by laheller** [apacha/sensor-fusion-demo#7]
@apacha 

...just two suggestions:

1.) Move the core part into a separate [AAR library](https://developer.android.com/studio/projects/android-library).
I did it and reused in my own Xamarin.Android project and it works perfectly.

2.) The demo app could have a feature something like 3D compass, so instead of cubes it could show labels like "North", "East", "South", "West", "Zenith", "Nadir".

BR,

Ladislav

**Comment by apacha** [comment]
Hi @laheller,

thanks for your suggestions. I think they are great and I always wanted to put something more meaningful on screen than a colourful cube, but never had the time to do so. Would you be willing to update the code and create a pull request? I'm more than happy to include you as contributor and release a new version with those improvements.

**Comment by laheller** [comment]
> Hi @laheller,
> 
> thanks for your suggestions. I think they are great and I always wanted to put something more meaningful on screen than a colourful cube, but never had the time to do so. Would you be willing to update the code and create a pull request? I'm more than happy to include you as contributor and release a new version with those improvements.

Hi @apacha 

I see that the cube rendering is implemented using OpenGL ES which is totally new for me.
In my projects I am using a higher level 3D API than OpenGL, but I can try. Probably the easiest way would be to create textures with proper text decoration and apply them to the surface of cubes.

BR,

Ladislav

**Comment by apacha** [comment]
I have no idea about open GL ES either, but just used this cube from a sample app. Please do replace it with a higher level API if you know any

**Comment by laheller** [comment]
@apacha 

OK, so far I only did the first part (see my very first comment above), here is the related commit:
https://github.com/laheller/sensor-fusion-demo/commit/500c9c84c02ce2a0d54e2bf1f7a13efc9fa47319

If you have time, please test it, whether the app can be built and whether it works on your Android device. Let me know if anything is wrong with the new project structure.
Meanwhile I am working on the demo app cubes "facelift"...

BR,

Ladislav

**Comment by laheller** [comment]
@apacha 
One part is done, I created a PR for it:
https://github.com/apacha/sensor-fusion-demo/pull/8

Still working on the second part - the cubes. Using (learning/trying) the [LibGDX](https://libgdx.com/) framework.

**Comment by laheller** [comment]
@apacha 

I implemented the 3D compass Fragment with nice textures using [libgdx](https://libgdx.com/) but somehow it does not like the current pager solution in the demo app. It force closes with error `E/AndroidGraphics( 7978): waiting for pause synchronization took too long; assuming deadlock and killing` when switching pages.

Thinking about to either:
1) Rewrite the logic of your demo app and instead of a pager simple using arrow buttons to switch between the various Orientation Providers
OR
2) Keep your demo app as it is and add another separate demo app with **only one** Fragment and paging **buttons** at the bottom left / bottom right corners of the screen.

What do you think?

BR,

Ladislav

**Comment by apacha** [comment]
I think the easiest solution would do. So if we don't use pager with multiple fragments, but instead simple buttons to switch between various orientation providers, that would be wonderful.

**Comment by laheller** [comment]
Hi @apacha 

There is a new PR where I reworked the demo app:
https://github.com/apacha/sensor-fusion-demo/pull/9

App uses the device's hardware volume up/down keys to switch between the orientation providers except the Calibrated Gyroscope, because a standalone gyroscope sensor cannot provide real orientation data.

**Comment by laheller** [comment]
@apacha 

Fixed my code based on your suggestions. Check last commit in the PR.

**Comment by apacha** [comment]
Merged your changes. Will do some preparations for the release now and then push 2.0.0 to the play store.

**Comment by apacha** [comment]
The app is now updated and available in the Google Play store
